import { useRef, useState, useMemo, useEffect } from 'react'
import * as THREE from 'three'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import { useGLTF } from '@react-three/drei'
import { Wars } from '../Components/Wars/WarComponent'
import { Color } from "three";

let wallMaterial = new THREE.MeshStandardMaterial({ color: "grey" })

function Map() {
    const [csvData, setCSVData] = useState(null);

    function mapRange(value, inputMin, inputMax, outputMin, outputMax) {
        // Clamp the value to the input range
        const clampedValue = Math.min(Math.max(value, inputMin), inputMax);

        // Calculate the percentage of the value within the input range
        const percentage = (clampedValue - inputMin) / (inputMax - inputMin);

        // Map the percentage to the output range
        const outputValue = percentage * (outputMax - outputMin) + outputMin;

        return outputValue;
    }

    useEffect(() => {
        let file = "./WW2_LocationData_Clean - GeoBattleData_YZ.csv";
        let handleRequest = (data) => {
            // console.log(data) 
            setCSVData(data);
        };
        // ------ Request Data
        d3.csv(file)
            .then(handleRequest);
    }, []);

    return (
        <>
            <Countries position={[1, 0, -5]} />
            {csvData && csvData.map((war, index) => {
                let long = mapRange(war.long, -180, 180, -27, 27);
                let lat = mapRange(war.lat, -90, 90, 13.5, -13.5);
                return <Wars colors={[
                    new Color("#F00511").convertLinearToSRGB(),
                    new Color("#B4040C").convertLinearToSRGB(),
                    new Color("#780208").convertLinearToSRGB(),
                    new Color("#500105").convertLinearToSRGB()
                ]} key={index} position={[long, 0.5, lat]} />
            })}
        </>
    )
}

export default Map

export function Countries({ position = [0, 0, 0] }) {
    let [fileNames, setFileNames] = useState([]);


    useMemo(() => {
        let files = ['./Maps/AE.glb',
            './Maps/AF.glb',
            './Maps/AI.glb',
            './Maps/AL.glb',
            './Maps/AM.glb',
            './Maps/AT.glb',
            './Maps/AW.glb',
            './Maps/BA.glb',
            './Maps/BB.glb',
            './Maps/BD.glb',
            './Maps/BE.glb',
            './Maps/BF.glb',
            './Maps/BG.glb',
            './Maps/BH.glb',
            './Maps/BI.glb',
            './Maps/BJ.glb',
            './Maps/BL.glb',
            './Maps/BM.glb',
            './Maps/BN.glb',
            './Maps/BO.glb',
            './Maps/BQBO.glb',
            './Maps/BQSA.glb',
            './Maps/BQSE.glb',
            './Maps/BR.glb',
            './Maps/BT.glb',
            './Maps/BW.glb',
            './Maps/BY.glb',
            './Maps/BZ.glb',
            './Maps/CD.glb',
            './Maps/CF.glb',
            './Maps/CG.glb',
            './Maps/CH.glb',
            './Maps/CI.glb',
            './Maps/CM.glb',
            './Maps/CO.glb',
            './Maps/CR.glb',
            './Maps/CU.glb',
            './Maps/Curve.glb',
            './Maps/Curve_001.glb',
            './Maps/Curve_002.glb',
            './Maps/Curve_003.glb',
            './Maps/Curve_004.glb',
            './Maps/Curve_005.glb',
            './Maps/Curve_006.glb',
            './Maps/Curve_007.glb',
            './Maps/Curve_008.glb',
            './Maps/Curve_009.glb',
            './Maps/Curve_010.glb',
            './Maps/Curve_011.glb',
            './Maps/Curve_012.glb',
            './Maps/Curve_013.glb',
            './Maps/Curve_014.glb',
            './Maps/Curve_015.glb',
            './Maps/Curve_016.glb',
            './Maps/Curve_017.glb',
            './Maps/Curve_018.glb',
            './Maps/Curve_019.glb',
            './Maps/Curve_020.glb',
            './Maps/Curve_021.glb',
            './Maps/Curve_022.glb',
            './Maps/Curve_023.glb',
            './Maps/Curve_024.glb',
            './Maps/Curve_025.glb',
            './Maps/Curve_026.glb',
            './Maps/Curve_027.glb',
            './Maps/Curve_028.glb',
            './Maps/Curve_029.glb',
            './Maps/Curve_030.glb',
            './Maps/Curve_031.glb',
            './Maps/Curve_032.glb',
            './Maps/Curve_033.glb',
            './Maps/Curve_034.glb',
            './Maps/Curve_035.glb',
            './Maps/Curve_036.glb',
            './Maps/Curve_037.glb',
            './Maps/Curve_038.glb',
            './Maps/Curve_039.glb',
            './Maps/Curve_040.glb',
            './Maps/Curve_041.glb',
            './Maps/Curve_042.glb',
            './Maps/Curve_043.glb',
            './Maps/Curve_044.glb',
            './Maps/Curve_045.glb',
            './Maps/Curve_046.glb',
            './Maps/Curve_047.glb',
            './Maps/Curve_048.glb',
            './Maps/Curve_049.glb',
            './Maps/Curve_050.glb',
            './Maps/Curve_051.glb',
            './Maps/Curve_052.glb',
            './Maps/Curve_053.glb',
            './Maps/Curve_054.glb',
            './Maps/Curve_055.glb',
            './Maps/Curve_056.glb',
            './Maps/Curve_057.glb',
            './Maps/Curve_058.glb',
            './Maps/Curve_059.glb',
            './Maps/Curve_060.glb',
            './Maps/Curve_061.glb',
            './Maps/Curve_062.glb',
            './Maps/Curve_063.glb',
            './Maps/Curve_064.glb',
            './Maps/Curve_065.glb',
            './Maps/Curve_066.glb',
            './Maps/Curve_067.glb',
            './Maps/Curve_068.glb',
            './Maps/Curve_069.glb',
            './Maps/Curve_070.glb',
            './Maps/Curve_071.glb',
            './Maps/Curve_072.glb',
            './Maps/Curve_073.glb',
            './Maps/Curve_074.glb',
            './Maps/Curve_075.glb',
            './Maps/Curve_076.glb',
            './Maps/Curve_077.glb',
            './Maps/Curve_078.glb',
            './Maps/Curve_079.glb',
            './Maps/Curve_080.glb',
            './Maps/Curve_081.glb',
            './Maps/Curve_082.glb',
            './Maps/Curve_083.glb',
            './Maps/Curve_084.glb',
            './Maps/Curve_085.glb',
            './Maps/Curve_086.glb',
            './Maps/Curve_087.glb',
            './Maps/Curve_088.glb',
            './Maps/Curve_089.glb',
            './Maps/Curve_090.glb',
            './Maps/Curve_091.glb',
            './Maps/Curve_092.glb',
            './Maps/Curve_093.glb',
            './Maps/Curve_094.glb',
            './Maps/Curve_095.glb',
            './Maps/Curve_096.glb',
            './Maps/Curve_097.glb',
            './Maps/Curve_098.glb',
            './Maps/Curve_099.glb',
            './Maps/Curve_100.glb',
            './Maps/Curve_101.glb',
            './Maps/Curve_102.glb',
            './Maps/Curve_103.glb',
            './Maps/Curve_104.glb',
            './Maps/Curve_105.glb',
            './Maps/Curve_106.glb',
            './Maps/Curve_107.glb',
            './Maps/Curve_108.glb',
            './Maps/Curve_109.glb',
            './Maps/Curve_110.glb',
            './Maps/Curve_111.glb',
            './Maps/Curve_112.glb',
            './Maps/Curve_113.glb',
            './Maps/Curve_114.glb',
            './Maps/Curve_115.glb',
            './Maps/Curve_116.glb',
            './Maps/Curve_117.glb',
            './Maps/Curve_118.glb',
            './Maps/Curve_119.glb',
            './Maps/Curve_120.glb',
            './Maps/Curve_121.glb',
            './Maps/Curve_122.glb',
            './Maps/Curve_123.glb',
            './Maps/Curve_124.glb',
            './Maps/Curve_125.glb',
            './Maps/Curve_126.glb',
            './Maps/Curve_127.glb',
            './Maps/Curve_128.glb',
            './Maps/Curve_129.glb',
            './Maps/Curve_130.glb',
            './Maps/Curve_131.glb',
            './Maps/Curve_132.glb',
            './Maps/Curve_133.glb',
            './Maps/Curve_134.glb',
            './Maps/Curve_135.glb',
            './Maps/Curve_136.glb',
            './Maps/Curve_137.glb',
            './Maps/Curve_138.glb',
            './Maps/Curve_139.glb',
            './Maps/Curve_140.glb',
            './Maps/Curve_141.glb',
            './Maps/Curve_142.glb',
            './Maps/Curve_143.glb',
            './Maps/Curve_144.glb',
            './Maps/Curve_145.glb',
            './Maps/Curve_146.glb',
            './Maps/Curve_147.glb',
            './Maps/Curve_148.glb',
            './Maps/Curve_149.glb',
            './Maps/Curve_150.glb',
            './Maps/Curve_151.glb',
            './Maps/Curve_152.glb',
            './Maps/Curve_153.glb',
            './Maps/Curve_154.glb',
            './Maps/Curve_155.glb',
            './Maps/Curve_156.glb',
            './Maps/Curve_157.glb',
            './Maps/Curve_158.glb',
            './Maps/Curve_159.glb',
            './Maps/Curve_160.glb',
            './Maps/Curve_161.glb',
            './Maps/Curve_162.glb',
            './Maps/Curve_163.glb',
            './Maps/Curve_164.glb',
            './Maps/Curve_165.glb',
            './Maps/Curve_166.glb',
            './Maps/Curve_167.glb',
            './Maps/Curve_168.glb',
            './Maps/Curve_169.glb',
            './Maps/Curve_170.glb',
            './Maps/Curve_171.glb',
            './Maps/Curve_172.glb',
            './Maps/Curve_173.glb',
            './Maps/Curve_174.glb',
            './Maps/Curve_175.glb',
            './Maps/Curve_176.glb',
            './Maps/Curve_177.glb',
            './Maps/Curve_178.glb',
            './Maps/Curve_179.glb',
            './Maps/Curve_180.glb',
            './Maps/Curve_181.glb',
            './Maps/Curve_182.glb',
            './Maps/Curve_183.glb',
            './Maps/Curve_184.glb',
            './Maps/Curve_185.glb',
            './Maps/Curve_186.glb',
            './Maps/Curve_187.glb',
            './Maps/Curve_188.glb',
            './Maps/Curve_189.glb',
            './Maps/Curve_190.glb',
            './Maps/Curve_191.glb',
            './Maps/Curve_192.glb',
            './Maps/Curve_193.glb',
            './Maps/Curve_194.glb',
            './Maps/Curve_195.glb',
            './Maps/Curve_196.glb',
            './Maps/Curve_197.glb',
            './Maps/Curve_198.glb',
            './Maps/Curve_199.glb',
            './Maps/Curve_200.glb',
            './Maps/Curve_201.glb',
            './Maps/Curve_202.glb',
            './Maps/Curve_203.glb',
            './Maps/Curve_204.glb',
            './Maps/Curve_205.glb',
            './Maps/Curve_206.glb',
            './Maps/Curve_207.glb',
            './Maps/Curve_208.glb',
            './Maps/Curve_209.glb',
            './Maps/Curve_210.glb',
            './Maps/Curve_211.glb',
            './Maps/Curve_212.glb',
            './Maps/Curve_213.glb',
            './Maps/Curve_214.glb',
            './Maps/Curve_215.glb',
            './Maps/Curve_216.glb',
            './Maps/Curve_217.glb',
            './Maps/Curve_218.glb',
            './Maps/Curve_219.glb',
            './Maps/Curve_220.glb',
            './Maps/Curve_221.glb',
            './Maps/Curve_222.glb',
            './Maps/Curve_223.glb',
            './Maps/Curve_224.glb',
            './Maps/Curve_225.glb',
            './Maps/Curve_226.glb',
            './Maps/Curve_227.glb',
            './Maps/Curve_228.glb',
            './Maps/Curve_229.glb',
            './Maps/Curve_230.glb',
            './Maps/Curve_231.glb',
            './Maps/Curve_232.glb',
            './Maps/Curve_233.glb',
            './Maps/Curve_234.glb',
            './Maps/Curve_235.glb',
            './Maps/Curve_236.glb',
            './Maps/Curve_237.glb',
            './Maps/Curve_238.glb',
            './Maps/Curve_239.glb',
            './Maps/Curve_240.glb',
            './Maps/Curve_241.glb',
            './Maps/Curve_242.glb',
            './Maps/Curve_243.glb',
            './Maps/Curve_244.glb',
            './Maps/Curve_245.glb',
            './Maps/Curve_246.glb',
            './Maps/Curve_247.glb',
            './Maps/Curve_248.glb',
            './Maps/Curve_249.glb',
            './Maps/Curve_250.glb',
            './Maps/Curve_251.glb',
            './Maps/Curve_252.glb',
            './Maps/Curve_253.glb',
            './Maps/Curve_254.glb',
            './Maps/Curve_255.glb',
            './Maps/Curve_256.glb',
            './Maps/Curve_257.glb',
            './Maps/Curve_258.glb',
            './Maps/Curve_259.glb',
            './Maps/Curve_260.glb',
            './Maps/Curve_261.glb',
            './Maps/Curve_262.glb',
            './Maps/Curve_263.glb',
            './Maps/Curve_264.glb',
            './Maps/Curve_266.glb',
            './Maps/Curve_267.glb',
            './Maps/Curve_268.glb',
            './Maps/Curve_269.glb',
            './Maps/Curve_270.glb',
            './Maps/Curve_271.glb',
            './Maps/Curve_272.glb',
            './Maps/Curve_273.glb',
            './Maps/Curve_274.glb',
            './Maps/Curve_275.glb',
            './Maps/Curve_276.glb',
            './Maps/Curve_277.glb',
            './Maps/Curve_278.glb',
            './Maps/Curve_279.glb',
            './Maps/Curve_280.glb',
            './Maps/Curve_281.glb',
            './Maps/Curve_282.glb',
            './Maps/Curve_283.glb',
            './Maps/Curve_284.glb',
            './Maps/Curve_285.glb',
            './Maps/Curve_286.glb',
            './Maps/Curve_287.glb',
            './Maps/Curve_288.glb',
            './Maps/Curve_289.glb',
            './Maps/Curve_290.glb',
            './Maps/Curve_291.glb',
            './Maps/Curve_292.glb',
            './Maps/Curve_293.glb',
            './Maps/Curve_294.glb',
            './Maps/Curve_295.glb',
            './Maps/Curve_296.glb',
            './Maps/Curve_297.glb',
            './Maps/Curve_298.glb',
            './Maps/Curve_299.glb',
            './Maps/Curve_300.glb',
            './Maps/CW.glb',
            './Maps/CZ_001.glb',
            './Maps/DE_001.glb',
            './Maps/DJ.glb',
            './Maps/DM.glb',
            './Maps/DO.glb',
            './Maps/DZ.glb',
            './Maps/EC.glb',
            './Maps/EE_001.glb',
            './Maps/EG.glb',
            './Maps/EH.glb',
            './Maps/ER.glb',
            './Maps/ES_001.glb',
            './Maps/ET.glb',
            './Maps/FI_001.glb',
            './Maps/GA.glb',
            './Maps/GD.glb',
            './Maps/GE_001.glb',
            './Maps/GF.glb',
            './Maps/GH.glb',
            './Maps/GL.glb',
            './Maps/GM.glb',
            './Maps/GN.glb',
            './Maps/GQ.glb',
            './Maps/GT.glb',
            './Maps/GU.glb',
            './Maps/GW.glb',
            './Maps/GY.glb',
            './Maps/HN.glb',
            './Maps/HR_001.glb',
            './Maps/HT.glb',
            './Maps/HU_001.glb',
            './Maps/IE_001.glb',
            './Maps/IL.glb',
            './Maps/IN.glb',
            './Maps/IQ.glb',
            './Maps/IR.glb',
            './Maps/IS_001.glb',
            './Maps/JM.glb',
            './Maps/JO.glb',
            './Maps/KE.glb',
            './Maps/KG.glb',
            './Maps/KH.glb',
            './Maps/KP.glb',
            './Maps/KR.glb',
            './Maps/KW.glb',
            './Maps/KZ.glb',
            './Maps/LA.glb',
            './Maps/LB.glb',
            './Maps/LC.glb',
            './Maps/LK.glb',
            './Maps/LR.glb',
            './Maps/LS.glb',
            './Maps/LT_001.glb',
            './Maps/LU_001.glb',
            './Maps/LV_001.glb',
            './Maps/LY.glb',
            './Maps/MA.glb',
            './Maps/MD_001.glb',
            './Maps/ME_001.glb',
            './Maps/MF.glb',
            './Maps/MG.glb',
            './Maps/MH.glb',
            './Maps/MK_001.glb',
            './Maps/ML.glb',
            './Maps/MM.glb',
            './Maps/MN.glb',
            './Maps/MQ.glb',
            './Maps/MR.glb',
            './Maps/MS.glb',
            './Maps/MV.glb',
            './Maps/MW.glb',
            './Maps/MX.glb',
            './Maps/MZ.glb',
            './Maps/NA.glb',
            './Maps/NE.glb',
            './Maps/NG.glb',
            './Maps/NI.glb',
            './Maps/NL_001.glb',
            './Maps/NP.glb',
            './Maps/NR.glb',
            './Maps/PA.glb',
            './Maps/PE.glb',
            './Maps/PK.glb',
            './Maps/PL_001.glb',
            './Maps/PS.glb',
            './Maps/PT_002.glb',
            './Maps/PW.glb',
            './Maps/PY.glb',
            './Maps/QA.glb',
            './Maps/RE.glb',
            './Maps/RO_001.glb',
            './Maps/RS_001.glb',
            './Maps/RW.glb',
            './Maps/SA.glb',
            './Maps/SD.glb',
            './Maps/SE_001.glb',
            './Maps/SI_001.glb',
            './Maps/SK_001.glb',
            './Maps/SL.glb',
            './Maps/SN.glb',
            './Maps/SO.glb',
            './Maps/SR.glb',
            './Maps/SS.glb',
            './Maps/SV.glb',
            './Maps/SX.glb',
            './Maps/SY.glb',
            './Maps/SZ.glb',
            './Maps/TD.glb',
            './Maps/TG.glb',
            './Maps/TH.glb',
            './Maps/TJ.glb',
            './Maps/TL.glb',
            './Maps/TM.glb',
            './Maps/TN.glb',
            './Maps/TV.glb',
            './Maps/TW.glb',
            './Maps/TZ.glb',
            './Maps/UA_001.glb',
            './Maps/UG.glb',
            './Maps/UY.glb',
            './Maps/UZ.glb',
            './Maps/VC.glb',
            './Maps/VE.glb',
            './Maps/VG.glb',
            './Maps/VN.glb',
            './Maps/XK_001.glb',
            './Maps/YE.glb',
            './Maps/YT.glb',
            './Maps/ZA.glb',
            './Maps/ZM.glb',
            './Maps/ZW.glb',];
        setFileNames(files);
    }, []);

    function returnContryObject() {
        return fileNames.map((file, index) => {
            let country = useGLTF(file);
            country.scene.children.forEach((mesh) => {
                // mesh.castShadow = true;
                mesh.receiveShadow = true;
                mesh.material = new THREE.MeshStandardMaterial({ color: "#555555" })
            });
            return (
                <RigidBody key={index} type='fixed' colliders='hull' position={[-29, -0.1, -8]} restitution={0.2} friction={0}>
                    <primitive object={country.scene} scale={[100, 20, 100]} />
                </RigidBody>
            )
        });
    }

    return (
        <group position={position}>
            {returnContryObject()}
        </group>
    )
}